name: Build & Release

on:
  push:
    branches: feat/pipeline

jobs:
  build_and_release:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 9.0.x
      - name: Install MAUI workload
        run: dotnet workload install maui-android
      - name: Build APK
        run: |
          cd MauiTemplate
          dotnet publish -c Release -f net9.0-android -o ./bin/Release/net9.0-android/publish `
            -p:AndroidPackageFormat=apk `
            -p:AndroidKeyStore=false `
            -p:ApplicationId=com.mauitemplate `
            -p:ApplicationName=MauiTemplate
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          files: MauiTemplate/bin/Release/net9.0-android/publish/*.apk
